version: '3'

services:
    deeba-hello:
        image: localhost:5000/first-image
        ports:
            - "5555:8081"
        deploy:
           replicas: 1
        networks:
            - default

    elk:
        image: sebp/elk
        ports:
          - "5601:5601"
          - "9200:9200"
          - "5044:5044"
        deploy:
           replicas: 1
        networks:
            - default

networks:
  default:
     driver: overlay